# Generated by Django 6.0 on 2025-12-14 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diplome', '0001_initial'),
        ('recrutement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='epreuve',
            name='diplome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diplome.diplome'),
            preserve_default=False,
        ),
    ]
