# Generated by Django 6.0 on 2025-12-14 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0001_initial'),
        ('diplome', '0001_initial'),
        ('recrutement', '0002_epreuve_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='offrediplome',
            name='diplome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diplome.diplome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offrerecrutement',
            name='categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorie.souscategorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postule',
            name='diplome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diplome.diplome'),
            preserve_default=False,
        ),
    ]
