# Generated by Django 6.0 on 2025-12-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recrutement', '0003_offrediplome_diplome_offrerecrutement_categorie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postule',
            name='lieu_n',
            field=models.DateField(blank=True, null=True),
        ),
    ]
